# Generated by Django 4.0 on 2022-07-29 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_reviewworker_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewworker',
            name='comment',
            field=models.TextField(max_length=300, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='reviewworker',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
