# Generated by Django 4.0 on 2022-08-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_alter_reviewworker_comment_alter_reviewworker_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewworker',
            name='rate',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=120),
        ),
    ]
