# Generated by Django 4.0 on 2022-08-06 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_alter_reviewworker_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewworker',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
