# Generated by Django 4.0 on 2022-12-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_alter_reviewworker_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewworker',
            name='comment',
            field=models.TextField(verbose_name='Review'),
        ),
    ]
