# Generated by Django 4.0 on 2022-06-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_booking_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_accept',
            new_name='accepted_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_denied',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
