# Generated by Django 4.0 on 2022-07-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_is_accept_booking_accepted_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='accepted_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('Denied', 'denied')], default='pending', max_length=20),
        ),
    ]
