# Generated by Django 4.0 on 2022-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_booking_accepted_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='accepted_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
