# Generated by Django 4.0 on 2022-07-25 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_profile_image'),
        ('service', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('available_status', models.BooleanField(default=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.worker')),
            ],
        ),
    ]
