# Generated by Django 4.0 on 2022-06-14 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_workercategory_remove_worker_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.workercategory'),
        ),
    ]
