# Generated by Django 4.0 on 2022-06-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_worker_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='category',
            new_name='category_name',
        ),
    ]
