# Generated by Django 4.0 on 2022-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_category_worker_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workercategory',
            name='service_picture',
            field=models.ImageField(blank=True, null=True, upload_to='service_image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-profile-image.png', null=True, upload_to='profile_image'),
        ),
    ]
