# Generated by Django 4.0 on 2022-06-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_workercategory_service_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default-profile-image.jpg', upload_to='profile_image'),
        ),
    ]
